### ISSUE TITLE
example needs updating for CP 7.x

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_BLE_Adafruit#14]
```
libraries/helpers/ble_adafruit/examples/ble_adafruit_feather_bluefruit_sense.py
90:mic_samples = ulab.zeros(MIC_NUM_SAMPLES, dtype=ulab.uint16)

libraries/helpers/ble_adafruit/examples/ble_adafruit_clue.py
64:mic_samples = ulab.zeros(MIC_NUM_SAMPLES, dtype=ulab.uint16)
```
these need to be updated to use `ulab.numpy`

**Comment by rsbohn** [comment]
(This is on the CLUE code.py at https://learn.adafruit.com/bluefruit-dashboard-web-bluetooth-chrome/circuitpython)

**Comment by jmangum** [comment]
Regarding @jepler comment, I have tested this using: 
```import ulab .numpy as np```
and
```mic_samples = np.zeros(MIC_NUM_SAMPLES, dtype=np.uint16)```

Also tested it using a perhaps cleaner:
```import ulab```
and
```mic_samples = ulab.numpy.zeros(MIC_NUM_SAMPLES, dtype=ulab.numpy.uint16)```
(which is, I believe, @jepler suggested change).

**Comment by rsbohn** [comment]
Seems like we're only using ulab.numpy to get an array of 16 bit values. Could probably use array.array instead.

**Comment by dhalbert** [comment]
> Seems like we're only using ulab.numpy to get an array of 16 bit values. Could probably use array.array instead.

We do
```py
            mic_svc.sound_samples = mic_samples - 32768
```
which relies on `ulab.numpy` operations.

**Comment by rsbohn** [comment]
Ah, I see. 

Looks like we're working on the same issue, you're just ahead of me.
