### ISSUE TITLE
it  is possible  add new service adafruit_ble_adafruit   and create mpy 

### ISSUE THREAD

**Issue by Geromino** [adafruit/Adafruit_CircuitPython_BLE_Adafruit#24]
i am looking  for  example service  battery  but i didnt  find any example   but  in https://adafruit.github.io/Adafruit_WebBluetooth_Dashboard/  i see   possible reading  https://github.com/adafruit/Adafruit_WebBluetooth_Dashboard/blob/master/js/script.js#L389  line 86

**Comment by dhalbert** [comment]
There is a standard battery service definition in https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/main/adafruit_ble/services/standard/__init__.py#L54. Is that what you want?

Do you want to present a battery service or query a battery service?

**Comment by Geromino** [comment]
Hi Dan ,  sorry for delay response 
thanks for the link very helpful and accurate  i see in nrfConnect mobile application   Battery Service
